### PR TITLE
Add support to micro 2.0

### PR DESCRIPTION
**Pull request by ghost**
Add support to micro 2.0

### CODE REVIEW

**Comment by pbsds** [comment]
`https://github.com/dwwmmn/micro-sunny-day/archive/0.1.2.zip` does not exist, since there is no git tag

**Comment by ghost** [comment]
@dwwmmn Need to create a new 0.1.2 tag for the plugin to be installed on micro v2

**Comment by dwwmmn** [comment]
I created the tag. `https://github.com/dwwmmn/micro-sunny-day/archive/0.1.2.zip` is now a valid URL but I don't know how to test if it works or not. I haven't used micro in a long time but `plugin install sunny-day-theme` doesn't seem to work anymore.

I seem to remember there being a list at https://github.com/micro-editor/plugin-channel but I don't see my repo listed there anymore. Maybe we need to submit another PR to that repo?

**Comment by ghost** [comment]
It would be a good idea to send a PR there adding this repo, and until the PR is accepted the installation can be done through this repository following the steps below (I tested it and the installation worked on the micro v2).

---

### Settings

Add this repo as a **pluginrepos** option in the `$XDG_CONFIG_HOME/micro/settings.json` file (it is necessary to restart the micro after this change):

```json title="~/.config/micro/settings.json"
  "pluginrepos": [
    "https://raw.githubusercontent.com/dwwmmn/micro-sunny-day/master/repo.json"
  ]
```

### Install

In your micro editor press **Ctrl-e** and run command:

```
> plugin install sunny-day-theme
```

*OR* Run in your shell

```shell
micro -plugin install sunny-day-theme
```

**Pull request merged**
